# SERVER & APP CONFIGURATION
server.port=8080
spring.application.name=expense-manager

# DATABASE CONNECTION (MySQL)
spring.datasource.url=JDBC:mysql://localhost:3306/expense_manager_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE SETTINGS
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# Set to 'none' as SQL scripts are managed manually
spring.jpa.hibernate.ddl-auto=none
# Strategy to map Java camelCase to SQL snake_case
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# SECURITY & CORS CONFIGURATION
app.security.public-routes=/api/v1/accounts/register, /api/v1/accounts/login, /api/v1/accounts/refresh-token, /test-ui
app.security.cors-origins=http://localhost:3000, http://localhost:3001, http://localhost:5173
app.security.api-key-header=X-expense-api-key
app.security.token-header=token

# JWT (JSON WEB TOKEN) CONFIGURATION
jwt.api-key=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NzE5MTUy
jwt.secret-token=d22a8a2897c822a51ce0b079ed67490b3ced782bc37a58e15ca0a120dc159fd9

# Expiration Times (in milliseconds)
# User Access (7 days), Admin Access (30 days), Refresh Token (1 year)
jwt.expiration.user-access=604800000
jwt.expiration.admin-access=2592000000
jwt.expiration.refresh-token=31536000000

# LOGGING CONFIGURATION
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.root=INFO
logging.level.com.talent.expense_manager=INFO

# Silence Hibernate and Spring Web spam
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.orm.jdbc.bind=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR
logging.level.org.springframework.web=INFO